### ISSUE TITLE
RangeError: offset is not uint

### ISSUE THREAD

**Issue by Kabloc** [hsk81/protobuf-rpc-js#2]
ControllerMessage.proto

```
syntax = "proto3";

package MyPackage;

message Void {
   int64 handshake = 9999;
}

message Boolean {
   bool val = 1;
   int64 handshake = 9999;
}

service Controller {
   rpc HavePassword (Void) returns (Boolean);
}

```

index.js

```
var express = require('express');
var app = express();
var ProtoBuf = require('protobufjs');
    ProtoBuf.Rpc = require('protobuf-rpc');

var builder = ProtoBuf.loadProtoFile("ControllerMessage.proto");
var My_controller = builder.build('MyPackage');
var controller_svc = new ProtoBuf.Rpc(My_controller.Controller, {
    transport: new ProtoBuf.Rpc.Transport.Xhr( {sync: true} ),
    url: 'http://127.0.0.1:5558'
});

app.get('/have_pswd', function (req, res) {
    var serv_req = new My_controller.Void();
    controller_svc.HavePassword(serv_req, function(error, serv_res) {
        if (error !== null) throw error;
        res.json(serv_res);
    });
});

var server = app.listen(9017, function(){
    var host = server.address().address;
    var port = server.address().port;

    console.log('Example app listening at http://%s:%s', host, port);
});
```

Result

```
 RangeError: offset is not uint
    at checkOffset (buffer.js:580:11)
    at SlowBuffer.Buffer.readUInt32LE (buffer.js:642:5)
    at null.rpcImpl (/home/kabloc/work/server_controller/node_modules/protobuf-rpc/index.js:322:39)
    at clazz.ServicePrototype.(anonymous function) [as HavePassword] (/home/kabloc/work/server_controller/node_modules/protobufjs/dist/protobuf.js:4050:38)
    at EventEmitter.app.listen.host (/home/kabloc/work/server_controller/index.js:15:17)
    at EventEmitter.emit (events.js:92:17)
    at null._onTimeout (/home/kabloc/work/server_controller/node_modules/protobuf-rpc/index.js:86:50)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by notexeditor** [comment]
@Kabloc: **Cannot reproduce** -- please see [tests](https://travis-ci.org/hsk81/protobuf-rpc-js) which run successfully on the latest Node version `6.x`, `5.x` and `4.x`. Is maybe your `handshake = 9999` number too great? Please solve yourself, and provide a [pull request](https://help.github.com/articles/using-pull-requests/) if necessary.
